(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);throw new Error("Cannot find module '"+o+"'")}var f=n[o]={exports:{}};t[o][0].call(f.exports,function(e){var n=t[o][1][e];return s(n?n:e)},f,f.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
!function(e,n,t){var r=t(e);return"function"==typeof define&&define.amd?define(r):("undefined"!=typeof module&&module.exports&&(module.exports=r),void(e[n]=r))}(this,"curry",function(){function e(n,r,o,u){function i(){var i=t.apply(r,arguments);return o-i.length<=0?n.apply(void 0===u?this:u,i):e(n,i,o,u)}return i.prototype=n.prototype,i}function n(n,t,r){return t="number"==typeof t?t:n.length,e(n,[],t,r)}{var t=[].concat;[].slice,{}.hasOwnProperty}return n});
},{}],2:[function(require,module,exports){
function async(t){setTimeout(function(){t()},0)}function checkStatus(){var t;if(!isReady)if(domReadyRE.test(document.readyState))for(isReady=!0;t=stack.shift();)async(t);else setTimeout(checkStatus,10)}var stack=[],domReadyRE=/interactive|complete|loaded/,isReady=!1;checkStatus(),module.exports=function(t){return"function"==typeof t?isReady?async(t):void stack.push(t):void 0};
},{}],3:[function(require,module,exports){
var events=require("bloody-events");module.exports=events.extend({constructor:function(t){if(events.constructor.call(this),arguments.length||(t={}),!t||"object"!=typeof t)throw new TypeError;this.data=t},get:function(t){return this.data[t]},set:function(t,e){var n,a=this.data[t],i=this.data.hasOwnProperty(t);this.data[t]=e,a!==e&&(n={key:t,oldValue:a,value:e},i||this.fireSync("add",n),this.fireSync("change",n))},remove:function(t){var e=this.data[t];delete this.data[t],void 0!==e&&(changeObject={key:t,oldValue:e,value:void 0},this.fireSync("remove",changeObject),this.fireSync("change",changeObject))},toString:function(){return JSON.stringify(this.data)},valueOf:function(){return this.data}});
},{"bloody-events":4}],4:[function(require,module,exports){
var klass=require("bloody-class"),immediate=require("bloody-immediate"),_slice=[].slice;module.exports=klass.extend({constructor:function(){this._events={}},destructor:function(){this._events={}},listen:function(e,t,n){for(var i,s=this._events[e]||(this._events[e]=[]),l=-1,r=s.length,c=this;++l<r;)if(s[l]===t)return;n&&(i=function(){return c.stopListening(e,t),t.apply(null,arguments)},i.listener=t),s.push(i||t)},listenOnce:function(e,t){this.listen(e,t,!0)},stopListening:function(e,t){var n,i;switch(arguments.length){case 0:this._events={};case 1:this._events[e]=null;default:if(n=this._events[e],i=n&&n.length,!i)return;for(;--i>-1;)if(n[i]===t||n[i].listener===t){n.splice(i,1);break}}},fire:function(e){function t(){++l>=s||(immediate.call(t),i[l].apply(null,n))}var n,i=this._events[e],s=i&&i.length,l=-1;s&&(n=_slice.call(arguments,1),immediate.call(t))},fireSync:function(e){function t(){++l>=s||(i[l].apply(null,n),t())}var n,i=this._events[e],s=i&&i.length,l=-1;s&&(n=_slice.call(arguments,1),t())}});
},{"bloody-class":5,"bloody-immediate":14}],5:[function(require,module,exports){
var extend=require("bloody-collections/lib/extend"),hasMethod=require("./lib/hasMethod"),create=require("./lib/create"),K=function(){};module.exports={extend:function(t){var e=create(this);return extend(e,t),e},create:function(){var t=create(this);return t._accessors={},hasMethod(t,"constructor")&&t.constructor.apply(t,arguments),t},destroy:function(){hasMethod(this,"destructor")&&this.destructor.apply(this,arguments),this._accessors={}},accessor:function(t){var e=this;return this._accessors.hasOwnProperty(t)?this._accessors[t]:this._accessors[t]=function(){return e[t].apply(e,arguments)}},constructor:K,destructor:K};
},{"./lib/create":6,"./lib/hasMethod":7,"bloody-collections/lib/extend":11}],6:[function(require,module,exports){
var toString=Object.prototype.toString,isNativeRE=RegExp("^"+String(toString).replace(/[.*+?^${}()|[\]\\]/g,"\\$&").replace(/toString| for [^\]]+/g,".*?")+"$");module.exports=Object.create&&isNativeRE.test(Object.create)?Object.create:function(t){function e(){}return e.prototype=t,new e};
},{}],7:[function(require,module,exports){
module.exports=function(n,o){return"function"==typeof n[o]};
},{}],8:[function(require,module,exports){
module.exports=[function(n,r){return function(){return n.call(r)}},function(n,r){return function(t){return n.call(r,t)}},function(n,r){return function(t,u){return n.call(r,t,u)}},function(n,r){return function(t,u,c){return n.call(r,t,u,c)}},function(n,r){return function(t,u,c,e){return n.call(r,t,u,c,e)}},function(n,r){return function(){return n.apply(r,arguments)}}];
},{}],9:[function(require,module,exports){
var callbacks=require("./_callbacks");module.exports=function(l,a,c){return void 0===a?l:c in callbacks?callbacks[c](l,a):callbacks[callbacks.length-1](l,a)};
},{"./_callbacks":8}],10:[function(require,module,exports){
var getKeys=require("./getKeys"),createCallback=require("./createCallback"),isArrayLike=require("./isArrayLike");module.exports=function(e,r,a){var i,l,t,s=-1,c=createCallback(r,a,3);if(e)if(isArrayLike(e))for(i=e.length;++s<i&&c(e[s],s,e)!==!1;);else for(l=getKeys(e),i=l.length;++s<i&&(t=l[s],c(e[t],t,e)!==!1););};
},{"./createCallback":9,"./getKeys":12,"./isArrayLike":13}],11:[function(require,module,exports){
function extend(e,t){return each(t,extendCallback,e),e}function extendCallback(e,t){return this?void(this[t]=e):!1}var each=require("./each");module.exports=extend;
},{"./each":10}],12:[function(require,module,exports){
var objectPrototype=Object.prototype,enumBugProperties=["constructor","hasOwnProperty","isPrototypeOf","propertyIsEnumerable",,"toLocaleString","toString","valueOf"],hasEnumBug=!objectPrototype.propertyIsEnumerable.call({constructor:1},"constructor"),_hasOwnProperty=objectPrototype.hasOwnProperty,hasObjectKeys="function"==typeof Object.keys,objectKeys=Object.keys;module.exports=function(e){var t,r,o,n;if(null==e)return[];if(hasObjectKeys)return objectKeys(e);r=[];for(t in e)_hasOwnProperty.call(e,t)&&r.push(t);if(hasEnumBug)for(t=-1,o=enumBugProperties.length;++t<o;)n=enumBugProperties[t],_hasOwnProperty.call(e,n)&&r.push(n);return r};
},{}],13:[function(require,module,exports){
var _hasOwnProperty={}.hasOwnProperty;module.exports=function(r){var e;return r&&parseInt(e=r.length,10)===e&&!e||_hasOwnProperty.call(r,e-1)};
},{}],14:[function(require,module,exports){
!function(e,t,n){return"function"==typeof define&&define.amd?define([],n):void("object"==typeof module&&module.exports?module.exports=n():e[t]=n())}(this,"immediate",function(){var e={},t=[],n=this,o=[].slice,i="immediate"+(Math.random()*(1<<30)|0),a=-1;return"function"==typeof n.setImmediate&&"function"==typeof n.clearImmediate?(e.call=function(e){if("function"!=typeof e)throw new TypeError("Expected a function");return n.setImmediate.apply(n,arguments)},e.cancel=function(){n.clearImmediate.apply(n,arguments)},e):n.addEventListener&&n.postMessage&&!n.importScripts?(e.call=function(e){if("function"!=typeof e)throw new TypeError("Expected a function");return a=t.push({fn:e,args:o.call(arguments,1),id:++a}),n.postMessage(i,"*"),a},e.cancel=function(e){var n=t.length;if(n)for(;--n;)t[n].id===e&&t.splice(n,1)},n.addEventListener("message",function(e){var o,a=e.source;a!=n||null!=a&&e.data!=i||(e.stopPropagation(),o=t.shift(),o&&o.fn.apply(null,o.args))},!1),e):(e.call=function(e){var t;if("function"!=typeof e)throw new TypeError("Expected a function");return t=o.call(arguments,1),setTimeout(function(){e.apply(null,t)},0)},e.cancel=function(e){clearTimeout(e)},e)});
},{}],15:[function(require,module,exports){
function timer(t,e){function n(){i=+new Date,a=(i-r)/e,t(a=1>a?a:1),i>o?1!=a&&requestAnimationFrame(function(){t(1)}):requestAnimationFrame(n)}var r=+new Date,o=r+e,i=r,a=0;requestAnimationFrame(n)}function getFirstNumber(){for(var t=-1,e=arguments.length;++t<e;)if(_toString.call(arguments[t])==NUMBER_CLASS)return arguments[t]}var win=window,doc=win.document,docEl=doc.documentElement,requestAnimationFrame=require("bloody-animationframe").requestAnimationFrame,_toString={}.toString,NUMBER_CLASS="[object Number]";module.exports=function(t,e){var n,r,o=win.pageYOffset||docEl.scrollTop||doc.body.scrollTop||0,i=win.pageXOffset||docEl.scrollLeft||doc.body.scrollLeft||0,a=_toString.call(t)==NUMBER_CLASS;a?(n=t,r=i):(n=getFirstNumber(t.top,o),r=getFirstNumber(t.left,i)),timer(function(t){win.scrollTo(i*(1-t)+r*t,o*(1-t)+n*t)},getFirstNumber(e,300))};
},{"bloody-animationframe":16}],16:[function(require,module,exports){
var animationFrame={},win=window,requestAnimationFrame=win.requestAnimationFrame||win.webkitRequestAnimationFrame||win.mozRequestAnimationFrame||win.oRequestAnimationFrame||win.msRequestAnimationFrame||function(n){return setTimeout(function(){n()},1e3/60)},cancelAnimationFrame=win.cancelAnimationFrame||win.webkitCancelAnimationFrame||win.webkitCancelRequestAnimationFrame||win.mozCancelAnimationFrame||win.oCancelAnimationFrame||win.msCancelAnimationFrame||function(n){clearTimeout(n)};module.exports={requestAnimationFrame:requestAnimationFrame,cancelAnimationFrame:cancelAnimationFrame};
},{}],17:[function(require,module,exports){
var map={id:"id",value:"value",selected:"selected",checked:"checked",href:"href","class":"className",className:"className",innerHTML:"innerHTML",textContent:"textContent",innerText:"innerText"};module.exports={set:function(e,t,n){return map[t]?void(e[map[t]]=n):void e.setAttribute(t,n)}};
},{}],18:[function(require,module,exports){
var klass=require("bloody-class"),template=require("../template"),attribute=require("./attribute");module.exports=klass.extend({ATTRIBUTE_BINDING:"data-cornea-binding",ATTRIBUTE_KEY:"data-cornea-key",ATTRIBUTE_ESCAPE:"data-cornea-escape",ATTRIBUTE_TEMPLATE:"data-cornea-template",CLASSNAME_BINDING:"cornea-binding",constructor:function(t,e){this.view=t,this.key=e},toString:function(t){return this.toNode(t).outerHTML},toNode:function(t){void 0==t&&(t={});var e,i=document.createElement(t.nodeName||"div"),a=t.hasOwnProperty("escape")?t.escape:!0;return i.className=this.CLASSNAME_BINDING+(t.className?" "+t.className:""),t.attributes&&Object.keys(t.attributes).forEach(function(e){attribute.set(i,e,t.attributes[e])}),i.setAttribute(this.ATTRIBUTE_BINDING,"innerHTML"),i.setAttribute(this.ATTRIBUTE_KEY,this.key),i.setAttribute(this.ATTRIBUTE_TEMPLATE,e=t.template||"#{*}"),a&&i.setAttribute(this.ATTRIBUTE_ESCAPE,""),attribute.set(i,"innerHTML",template(e,this.view.data&&this.view.data[this.key],a)),i},bindAttribute:function(t,e,i){void 0==i&&(i={});var a,s=i.hasOwnProperty("escape")?i.escape:!0;t.setAttribute(this.ATTRIBUTE_BINDING,e),t.setAttribute(this.ATTRIBUTE_KEY,this.key),t.setAttribute(this.ATTRIBUTE_TEMPLATE,a=i.template||"#{*}"),t.className=(t.className+" "+this.CLASSNAME_BINDING).trim(),s&&t.setAttribute(this.ATTRIBUTE_ESCAPE,""),attribute.set(t,e,template(a,this.view.data&&this.view.data[this.key],s))}});
},{"../template":35,"./attribute":17,"bloody-class":23}],19:[function(require,module,exports){
var matches=require("./matches");module.exports=function(r,t,e){var a=this;return t?function(n){var c;return(c=matches(r,n.target,t))?a[e].call(a,n,c):void 0}:function(t){return a[e].call(a,t,r)}};
},{"./matches":21}],20:[function(require,module,exports){
function listen(e){e._listener=createListener.call(this,this.element,e.selector,e.listener),this.element.addEventListener(e.type,e._listener,!!e.capture)}function stopListening(e){this.element.removeEventListener(e.type,e._listener,!!e.capture)}var createListener=require("./createListener");module.exports={listen:function(e){e.events&&e.events.forEach(listen,e)},stopListening:function(e){e.events&&e.events.forEach(stopListening,e)}};
},{"./createListener":19}],21:[function(require,module,exports){
var docEl=document.documentElement,nativeMatchesSelector=docEl.matches||docEl.matchesSelector||docEl.webkitMatchesSelector||docEl.mozMatchesSelector||docEl.oMatchesSelector||docEl.msMatchesSelector;if(!nativeMatchesSelector)throw new Error("this browser does not support .matchesSelector");module.exports=function(e,t,c){if(t==e)return!1;if(nativeMatchesSelector.call(t,c))return t;for(;(t=t.parentNode)&&t!=e&&t.nodeType==t.ELEMENT_NODE;)if(nativeMatchesSelector.call(t,c))return t;return!1};
},{}],22:[function(require,module,exports){
var eventClass=require("bloody-events"),events=require("./events"),binding=require("./binding"),attribute=require("./binding/attribute"),template=require("./template"),extend=require("./utils/extend"),empty=function(){return""},_forEach=[].forEach;module.exports=eventClass.extend({constructor:function(e){eventClass.constructor.call(this),extend(this,e),("string"!=typeof this.element||(this.element=document.querySelector(this.element),this.element))&&(this.element||(this.element=document.createElement("div")),"function"==typeof this.initialize&&this.initialize.apply(this,arguments),this.initEvents())},destructor:function(){"function"==typeof this.release&&this.release.apply(this,arguments),this.removeEvents()},initEvents:function(){events.listen(this)},removeEvents:function(){events.stopListening(this)},binding:function(e){return binding.create(this,e)},template:empty,render:function(){var e=this.template(this.data);return this.element.innerHTML="","string"==typeof e?(this.element.innerHTML=e,this.updateBindings()):void(e&&e.nodeType&&(this.element.innerHTML="",this.element.appendChild(e),this.updateBindings()))},updateBindings:function(){this.bindings=this.element.querySelectorAll("."+binding.CLASSNAME_BINDING)},update:function(e,t){_forEach.call(this.bindings,function(i){var n,s,r;i.getAttribute(binding.ATTRIBUTE_KEY)==e&&(n=i.getAttribute(binding.ATTRIBUTE_BINDING),s=i.getAttribute(binding.ATTRIBUTE_TEMPLATE),r=template(s,t,i.hasAttribute(binding.ATTRIBUTE_ESCAPE)),attribute.set(i,n,r))})}});
},{"./binding":18,"./binding/attribute":17,"./events":20,"./template":35,"./utils/extend":36,"bloody-events":32}],23:[function(require,module,exports){
module.exports=require(5)
},{"./lib/create":24,"./lib/hasMethod":25,"bloody-collections/lib/extend":29}],24:[function(require,module,exports){
module.exports=require(6)
},{}],25:[function(require,module,exports){
module.exports=require(7)
},{}],26:[function(require,module,exports){
module.exports=require(8)
},{}],27:[function(require,module,exports){
module.exports=require(9)
},{"./_callbacks":26}],28:[function(require,module,exports){
module.exports=require(10)
},{"./createCallback":27,"./getKeys":30,"./isArrayLike":31}],29:[function(require,module,exports){
module.exports=require(11)
},{"./each":28}],30:[function(require,module,exports){
module.exports=require(12)
},{}],31:[function(require,module,exports){
module.exports=require(13)
},{}],32:[function(require,module,exports){
module.exports=require(4)
},{"bloody-class":23,"bloody-immediate":33}],33:[function(require,module,exports){
module.exports=require(14)
},{}],34:[function(require,module,exports){
function escapeHTML(e){return htmlChars[e]}var htmlChars={"&":"&amp;","<":"&lt;",">":"&gt;","'":"&quot;",'"':"&#39;"},keys=Object.keys(htmlChars),regExp=RegExp("["+keys.join("")+"]","g");module.exports=function(e){return e.replace(regExp,escapeHTML)};
},{}],35:[function(require,module,exports){
var escape=require("./escape"),templateRE=/#\{\*\}/g;module.exports=function(e,a,p){return null==a&&(a=""),p&&(a=escape(a)),e.replace(templateRE,a)};
},{"./escape":34}],36:[function(require,module,exports){
module.exports=function(o,c){c&&Object.keys(c).forEach(function(e){o[e]=c[e]})};
},{}],37:[function(require,module,exports){
var domReady=require("bloody-domready");require("./lib/classList"),domReady(function(){require("./views/images").create(),require("./views/column").create(),require("./views/post").create(),require("./views/posts").create(),require("./views/tagfilters").create(),require("./views/scroll").create()});
},{"./lib/classList":38,"./views/column":40,"./views/images":41,"./views/post":42,"./views/posts":43,"./views/scroll":44,"./views/tagfilters":45,"bloody-domready":2}],38:[function(require,module,exports){
!function(){function t(t){this.el=t;for(var n=t.className.replace(/^\s+|\s+$/g,"").split(/\s+/),i=0;i<n.length;i++)e.call(this,n[i])}function n(t,n,i){Object.defineProperty?Object.defineProperty(t,n,{get:i}):t.__defineGetter__(n,i)}if(!("undefined"==typeof window.Element||"classList"in document.documentElement)){var i=Array.prototype,e=i.push,s=i.splice,o=i.join;t.prototype={add:function(t){this.contains(t)||(e.call(this,t),this.el.className=this.toString())},contains:function(t){return-1!=this.el.className.indexOf(t)},item:function(t){return this[t]||null},remove:function(t){if(this.contains(t)){for(var n=0;n<this.length&&this[n]!=t;n++);s.call(this,n,1),this.el.className=this.toString()}},toString:function(){return o.call(this," ")},toggle:function(t){return this.contains(t)?this.remove(t):this.add(t),this.contains(t)}},window.DOMTokenList=t,n(Element.prototype,"classList",function(){return new t(this)})}}();
},{}],39:[function(require,module,exports){
var observable=require("bloody-observable");module.exports=observable.create();
},{"bloody-observable":3}],40:[function(require,module,exports){
var cornea=require("cornea"),tags=require("../models/tags");module.exports=cornea.extend({element:".js-Column",events:[{type:"change",selector:".js-ToggleTag",listener:"updateTags"}],updateTags:function(e,a){return a.checked?void tags.set(a.value,!0):void tags.remove(a.value)}});
},{"../models/tags":39,"cornea":22}],41:[function(require,module,exports){
var cornea=require("cornea"),curry=require("bloody-curry");module.exports=cornea.extend({element:document.documentElement,initialize:function(){var e=this.element.querySelectorAll(".js-AnimateLoad");[].forEach.call(e,curry(this.addLoadedClass)(null))},events:[{type:"load",selector:".js-AnimateLoad",capture:!0,listener:"addLoadedClass"}],addLoadedClass:function(e,a){var d=a.classList;a.complete&&(d.remove("js-AnimateLoad"),d.add("js-Loaded"))}});
},{"bloody-curry":1,"cornea":22}],42:[function(require,module,exports){
var cornea=require("cornea");module.exports=cornea.extend({element:".putainde-Post-readingTime-value",initialize:function(){this.parseWordsPerMinute(),this.setTooltipWording(),this.render(),this.show()},setTooltipWording:function(){var e=this.element.parentNode,t=e.getAttribute("data-tip");e.setAttribute("data-tip",t.replace("{{wpm}}",this.wordsPerMinute))},wordsPerMinute:250,parseWordsPerMinute:function(){var e="data-readingTime-wpm",t=this.element.parentNode;t.hasAttribute(e)&&(this.wordsPerMinute=parseInt(t.getAttribute(e),10))},getDuration:function(){var e=document.querySelector(".putainde-Post-md"),t=e.textContent||e.innerText;return Math.round(t.split(/\s+|\s*\.\s*/).length/this.wordsPerMinute)},template:function(){return document.createTextNode(this.getDuration())},show:function(){var e=this.element.parentNode;e.classList.remove("putainde-Post-readingTime--hidden")}});
},{"cornea":22}],43:[function(require,module,exports){
var cornea=require("cornea"),tags=require("../models/tags");module.exports=cornea.extend({element:".js-Posts",initialize:function(){var s=this;this.posts=[].slice.call(this.element.querySelectorAll(".js-Post")),this.noPosts=this.element.querySelector(".js-NoPosts"),this.parsePosts(),tags.listen("change",function(){s.updatePosts(tags.valueOf())})},map:{},hidden:[],parsePosts:function(){function s(s){var e,i=s.querySelectorAll(".js-Tag"),n=-1,a=i.length;for(++t,e=this.map[t]={},e.element=s;++n<a;)e[i[n].getAttribute("data-tag")]=!0}var t=-1;this.posts.forEach(s,this)},updatePosts:function(s){var t,e,i;this.showAll();for(t in s)for(e in this.map)this.map[e][t]||(i=this.map[e].element,-1==this.hidden.indexOf(i)&&(this.hidden.push(i),i.classList.add("putainde-List-item--hidden")));this.hidden.length==this.posts.length&&this.noPosts.classList.remove("putainde-Message--hidden")},showAll:function(){var s;for(this.noPosts.classList.add("putainde-Message--hidden");s=this.hidden.shift();)s.classList.remove("putainde-List-item--hidden")}});
},{"../models/tags":39,"cornea":22}],44:[function(require,module,exports){
var cornea=require("cornea"),smoothScroll=require("bloody-scroll");module.exports=cornea.extend({element:document.body,initialize:function(){this.scrollTo()},events:[{type:"click",selector:".js-ScrollTo",listener:"scrollTo"}],scrollTo:function(e,o){var t,l=window.location.hash;o&&(l=o.hash,e.preventDefault()),l&&"#"!=l&&(t=document.getElementById(l.slice(1)),t&&setTimeout(function(){var e=t.getBoundingClientRect();smoothScroll(e.top+window.pageYOffset,500)},300))}});
},{"bloody-scroll":15,"cornea":22}],45:[function(require,module,exports){
var cornea=require("cornea");module.exports=cornea.extend({element:document.body,events:[{type:"click",selector:".js-ToggleFilters",listener:"toggleFilters"},{type:"click",selector:".js-CloseFilters",listener:"closeFilters"}],toggleFilters:function(){this.element.classList.toggle("putainde-Body--tagFiltersOpened")},closeFilters:function(){this.element.classList.remove("putainde-Body--tagFiltersOpened")}});
},{"cornea":22}]},{},[37])